/*
ReVisE: Remote visualization environment for large datasets
Copyright (C) 2021 Stepan Orlov, Alexey Kuzin, Alexey Zhuravlev, Vyacheslav Reshetnikov, Egor Usik, Vladislav Kiev, Andrey Pyatlin

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see https://www.gnu.org/licenses/agpl-3.0.en.html.

*/

#pragma once

#include "ipc/SharedMemory.h"

namespace s3vs
{

/// @brief Specification of format and location for output frames generated by the visualization server.
struct VsControllerFrameOutput
{
    /// @brief Location of visualized frames in shared memory.
    std::shared_ptr<SharedMemory> shmem;

    /// @brief Frame size, in bytes, not including frame number.
    std::size_t frameSize = 0;

    /// @brief Frame width, in pxiels.
    int frameWidth = 0;

    /// @brief Frame height, in pxiels.
    int frameHeight = 0;
};

} // namespace s3vs
